name: Drupal9
recipe: drupal9
config:
  webroot: docroot
  php: '8.0'

services:
  database:
    portforward: 3308
    creds:
      user: drupal
      password: drupal
      database: drupal
  pma:
    type: phpmyadmin
    hosts:
      - database

